# Rad s matricama - numpy

numpy je Python-ov modul za rad s matricama.

In [1]:
import numpy as np

** Stvaranje vektora i matrice **

In [2]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [3]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

** Dimenzija vektora i matrice **

In [4]:
y.shape

(3,)

In [5]:
x.shape

(2, 3)

** Postavljanje vrijednosti **

In [6]:
y[2] = 100
y

array([  1,   2, 100])

In [7]:
x[1, 0] = 100
x

array([[  1,   2,   3],
       [100,   5,   6]])

** Stvaranje nul matrice **

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 3. Minimalna udaljenost

In [10]:
from opj_v03_test import *

## 3.1. Matrica udaljenosti

Napravi funkciju ** edit_dist_mx() ** po sljedećim ulaznim i izlaznim podacima
* ulaz:
    * ** s1 ** tekst
    * ** s2 ** tekst
* izlaz:
    * matrica udaljenosti između s1 i s2
    
Na primjer, matrica udaljenosti za s1 = "nos" i s2 = "noj" je

    [[0, 1, 2, 3],  
     [1, 0, 1, 2],  
     [2, 1, 0, 1],  
     [3, 2, 1, 2]]

Odnosno 

    s	3	2	1	2  
    o	2	1	0	1  
    n	1	0	1	2  
    #	0	1	2	3  
         #	n	o	j  

In [11]:
def edit_dist_mx(s1, s2):
    return


def edit_dist(s1, s2):
    return edit_dist_mx(s1, s2)[-1, -1]
    

testname(edit_dist)
test_dist(edit_dist_mx, edit_dist, ('nos','noj'), ([[0, 1, 2, 3], 
                                                    [1, 0, 1, 2], 
                                                    [2, 1, 0, 1], 
                                                    [3, 2, 1, 2]], 2))
test_dist(edit_dist_mx, edit_dist, ('osa','bosa'), ([[0, 1, 2, 3, 4], 
                                                     [1, 2, 1, 2, 3], 
                                                     [2, 3, 2, 1, 2], 
                                                     [3, 4, 3, 2, 1]], 1))
test_dist(edit_dist_mx, edit_dist, ('bosa','osa'), ([[0, 1, 2, 3], 
                                                     [1, 2, 3, 4], 
                                                     [2, 1, 2, 3], 
                                                     [3, 2, 1, 2], 
                                                     [4, 3, 2, 1]], 1))
test_dist(edit_dist_mx, edit_dist, ('paliti','piti'), ([[0, 1, 2, 3, 4], 
                                                        [1, 0, 1, 2, 3], 
                                                        [2, 1, 2, 3, 4], 
                                                        [3, 2, 3, 4, 5], 
                                                        [4, 3, 2, 3, 4], 
                                                        [5, 4, 3, 2, 3], 
                                                        [6, 5, 4, 3, 2]], 2))
test_dist(edit_dist_mx, edit_dist, ('paliti','pisati'), ([[0, 1, 2, 3, 4, 5, 6], 
                                                          [1, 0, 1, 2, 3, 4, 5], 
                                                          [2, 1, 2, 3, 2, 3, 4], 
                                                          [3, 2, 3, 4, 3, 4, 5], 
                                                          [4, 3, 2, 3, 4, 5, 4], 
                                                          [5, 4, 3, 4, 5, 4, 5], 
                                                          [6, 5, 4, 5, 6, 5, 4]], 4))


EDIT_DIST
------------------------------------------------------------
X
X
X
X
X


Napravi funkciju ** align() ** po sljedećim ulaznim i izlaznim podacima
* ulaz:
    * ** s1 ** tekst
    * ** s2 ** tekst
* izlaz:
    * Uređeni par ** (as1, as2) ** gdje je as1 poravnanje od s1, a as2 poravnanje od s2 (prilikom poravnanja koristiti "-")
    
Primjer, poravnanje od 'paliti' i 'pisati':

    pali--ti  
    p--isati


In [12]:
def align(s1, s2):
    return

testname(align)
test_alignment(align, ('nos','noj'), ('nos', 'noj'))
test_alignment(align, ('osa','bosa'), ('-osa', 'bosa'))
test_alignment(align, ('bosa','osa'), ('bosa', '-osa'))
test_alignment(align, ('paliti','piti'), ('paliti', 'p--iti'))
test_alignment(align, ('paliti','pisati'), ('pali--ti', 'p--isati'))
test_alignment(align, ('blindiram', 'navigiram'), ('blin-di--ram', '---navigiram'))


ALIGN
------------------------------------------------------------
X
X
X
X
X
X
