# Rad s matricama - numpy

numpy je Python-ov modul za rad s matricama.

In [1]:
import numpy as np

** Stvaranje vektora i matrice **

In [2]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [3]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

** Dimenzija vektora i matrice **

In [4]:
y.shape

(3,)

In [5]:
x.shape

(2, 3)

** Postavljanje vrijednosti **

In [6]:
y[2] = 100
y

array([  1,   2, 100])

In [7]:
x[1, 0] = 100
x

array([[  1,   2,   3],
       [100,   5,   6]])

** Stvaranje nul matrice **

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 3. Minimalna udaljenost

## 3.1. Matrica udaljenosti

Napravi funkciju ** edit_dist_mx() ** po sljedećim ulaznim i izlaznim podacima
* ulaz:
    * ** s1 ** tekst
    * ** s2 ** tekst
* izlaz:
    * matrica udaljenosti između s1 i s2
    
Na primjer, matrica udaljenosti za s1 = "nos" i s2 = "noj" je

    [[0, 1, 2, 3],  
     [1, 0, 1, 2],  
     [2, 1, 0, 1],  
     [3, 2, 1, 2]]

Odnosno 

    s	3	2	1	2  
    o	2	1	0	1  
    n	1	0	1	2  
    #	0	1	2	3  
         #	n	o	j  

In [10]:
from opj_v03_test import *

def edit_dist_mx(s1, s2):
    n, m = len(s1), len(s2)
    mx = np.zeros((n + 1, m + 1), dtype=int)

    for i in range(n + 1):
        mx[i, 0] = i
    for j in range(m + 1):
        mx[0, j] = j

    for i in range(1, n + 1):
        for j in range(1, m + 1):
            mx[i, j] = min(
                mx[i - 1, j] + 1,
                mx[i, j - 1] + 1,
                mx[i - 1, j - 1] + (2 if s1[i - 1] != s2[j - 1] else 0)
            )

    return mx


def edit_dist(s1, s2):
    return edit_dist_mx(s1, s2)[-1, -1]
    

testname(edit_dist)
test_dist(edit_dist_mx, edit_dist, ('nos','noj'), ([[0, 1, 2, 3], 
                                                    [1, 0, 1, 2], 
                                                    [2, 1, 0, 1], 
                                                    [3, 2, 1, 2]], 2))
test_dist(edit_dist_mx, edit_dist, ('osa','bosa'), ([[0, 1, 2, 3, 4], 
                                                     [1, 2, 1, 2, 3], 
                                                     [2, 3, 2, 1, 2], 
                                                     [3, 4, 3, 2, 1]], 1))
test_dist(edit_dist_mx, edit_dist, ('bosa','osa'), ([[0, 1, 2, 3], 
                                                     [1, 2, 3, 4], 
                                                     [2, 1, 2, 3], 
                                                     [3, 2, 1, 2], 
                                                     [4, 3, 2, 1]], 1))
test_dist(edit_dist_mx, edit_dist, ('paliti','piti'), ([[0, 1, 2, 3, 4], 
                                                        [1, 0, 1, 2, 3], 
                                                        [2, 1, 2, 3, 4], 
                                                        [3, 2, 3, 4, 5], 
                                                        [4, 3, 2, 3, 4], 
                                                        [5, 4, 3, 2, 3], 
                                                        [6, 5, 4, 3, 2]], 2))
test_dist(edit_dist_mx, edit_dist, ('paliti','pisati'), ([[0, 1, 2, 3, 4, 5, 6], 
                                                          [1, 0, 1, 2, 3, 4, 5], 
                                                          [2, 1, 2, 3, 2, 3, 4], 
                                                          [3, 2, 3, 4, 3, 4, 5], 
                                                          [4, 3, 2, 3, 4, 5, 4], 
                                                          [5, 4, 3, 4, 5, 4, 5], 
                                                          [6, 5, 4, 5, 6, 5, 4]], 4))


EDIT_DIST
------------------------------------------------------------
OK	udaljenost između 'nos' i 'noj' je 2
s	3	2	1	2
o	2	1	0	1
n	1	0	1	2
#	0	1	2	3
 	#	n	o	j

OK	udaljenost između 'osa' i 'bosa' je 1
a	3	4	3	2	1
s	2	3	2	1	2
o	1	2	1	2	3
#	0	1	2	3	4
 	#	b	o	s	a

OK	udaljenost između 'bosa' i 'osa' je 1
a	4	3	2	1
s	3	2	1	2
o	2	1	2	3
b	1	2	3	4
#	0	1	2	3
 	#	o	s	a

OK	udaljenost između 'paliti' i 'piti' je 2
i	6	5	4	3	2
t	5	4	3	2	3
i	4	3	2	3	4
l	3	2	3	4	5
a	2	1	2	3	4
p	1	0	1	2	3
#	0	1	2	3	4
 	#	p	i	t	i

OK	udaljenost između 'paliti' i 'pisati' je 4
i	6	5	4	5	6	5	4
t	5	4	3	4	5	4	5
i	4	3	2	3	4	5	4
l	3	2	3	4	3	4	5
a	2	1	2	3	2	3	4
p	1	0	1	2	3	4	5
#	0	1	2	3	4	5	6
 	#	p	i	s	a	t	i



Napravi funkciju ** align() ** po sljedećim ulaznim i izlaznim podacima
* ulaz:
    * ** s1 ** tekst
    * ** s2 ** tekst
* izlaz:
    * Uređeni par ** (as1, as2) ** gdje je as1 poravnanje od s1, a as2 poravnanje od s2 (prilikom poravnanja koristiti "-")
    
Primjer, poravnanje od 'paliti' i 'pisati':

    pali--ti  
    p--isati


In [11]:
def align(s1, s2):
    D = edit_dist_mx(s1, s2)
    NS, NT = '', ''
    state = n, m = len(s1), len(s2)
    i, j = n - 1, m - 1
    while state != (0, 0):
        n, m = state
        next_states = {D[x, y]: (x, y)
                       for x, y in [(n - 1, m), (n, m - 1), (n - 1, m - 1)]
                       if x >= 0 and y >= 0}
        next_state = next_states[min(next_states)]
        nn, mm = next_state

        if nn < n:
            NS = s1[i] + NS
            i -= 1
        else:
            NS = '-' + NS

        if mm < m:
            NT = s2[j] + NT
            j -= 1
        else:
            NT = '-' + NT

        state = next_state

    return NS, NT

testname(align)
test_alignment(align, ('nos','noj'), ('nos', 'noj'))
test_alignment(align, ('osa','bosa'), ('-osa', 'bosa'))
test_alignment(align, ('bosa','osa'), ('bosa', '-osa'))
test_alignment(align, ('paliti','piti'), ('paliti', 'p--iti'))
test_alignment(align, ('paliti','pisati'), ('pali--ti', 'p--isati'))
test_alignment(align, ('blindiram', 'navigiram'), ('blin-di--ram', '---navigiram'))


ALIGN
------------------------------------------------------------
OK	poravnanje od 'nos' i 'noj':
nos
noj

OK	poravnanje od 'osa' i 'bosa':
-osa
bosa

OK	poravnanje od 'bosa' i 'osa':
bosa
-osa

OK	poravnanje od 'paliti' i 'piti':
paliti
p--iti

OK	poravnanje od 'paliti' i 'pisati':
pali--ti
p--isati

OK	poravnanje od 'blindiram' i 'navigiram':
blin-di--ram
---navigiram

